### ISSUE TITLE
'Aggregates' carousel does not work as expected

### ISSUE THREAD

**Issue by PPrasai** [covidsimteam/prox-e#66]
**Bug Description:**
All carousels stop working when any of the menu item under 'Aggregates' carousel is selected. To make it work again I have to click on a non-carousel menu item.

**Steps To Reproduce:**
1. Click on `Aggregates` menu item on the left side menu
2. Click on any menu item under the `Aggregates` menu. The corresponding page should load.
3. Click on any other menu item which has a carousel dropdown sub-menu, except the sub-items of the `Aggregate`
4. See error (other carousels, including the `Aggregates` does not work)

**Expected Behavior:**
Clicking on any carousel-enabled menu item at any point should expand/collapse the carousel

**Screenshots:**
![Screenshot at 2020-08-28 12-46-39](https://user-images.githubusercontent.com/11856653/91531906-404fe780-e92d-11ea-951a-c55c7f0659a7.png)

**Desktop:**
 - OS: [ArchLinux]
 - Browser [Firefox]
 - Version [79.0]

**Comment by risavkarna** [comment]
Expected to be fixed by #70
