### ISSUE TITLE
Radio Buttons Error

### ISSUE THREAD

**Issue by aayushkafle** [covidsimteam/prox-e#85]
**Bug Description:**
I encountered bugs related to the radio buttons in our forms. The bugs prevent selecting the options between two or more different groups.

**Steps To Reproduce:**
1. Go to https://nep.work/hub/home
2. Click on "Forms" from the side panel
3. Scroll down to any form and try clicking any radio (o) buttons.
4. In the "Form A," the buttons on the first part of the form are not clickable. For all other forms, the buttons for different groups do not behave normally.

**Expected Behavior:**
For eg, we have to select one of the genders and on the same form, we have to select one of the PCR results. Normally it is expected to select one option from the gender group and one option from the PCR result group i.e. one option per group of options (radio buttons). However, in our forms, we can select only one option in the entire form.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 80.0.1

**Comment by risavkarna** [comment]
@Cryptokripa's solution to use `nb-radio-group` over `mat-radio-group` will be used as the preferred solution. Closing this issue in lieu of her solution.
