### ISSUE TITLE
Finalize a design for the data-entry dashboard

### ISSUE THREAD

**Issue by PPrasai** [covidsimteam/prox-e#87]
**Feature Description:**
We need a separate dashboard which enables `case investigators` and `contact tracers` to efficiently assign tasks and fill various forms.

**Solution Description:**
![Screenshot at 2020-09-10 18-20-13](https://user-images.githubusercontent.com/11856653/92729619-52e90880-f392-11ea-8439-3e689de33c88.png)

This is the first design prototype.

**Comment by risavkarna** [comment]
Great job guys. Congrats on an important task well-done with such fine team coordination and quality code.
