### ISSUE TITLE
Prepare active/pending task component for data-entry dashboard

### ISSUE THREAD

**Issue by PPrasai** [covidsimteam/prox-e#90]
**Feature Description:**
We need an `nbCard` displaying `pending` and `complete` tasks for each registered user as shown in Issue #87 .

**Solution Description:**
Count the number of pending tasks and show them as `Pending`, count the number of complete tasks and show them as `Complete`. Users with role `Coordinator` and `Mayor / Admin` should these stats aggregated across all users. Rest of the users should see these stats for tasks that has been assigned to them.

**Comment by risavkarna** [comment]
@PPrasai, is the counting part done?

**Comment by PPrasai** [comment]
Not yet. Will do after finishing `Add new cases` implementation.
