### ISSUE TITLE
UI fixes for forms 

### ISSUE THREAD

**Issue by Cryptokripa** [covidsimteam/prox-e#92]
**Feature Description:**

**Solution Description:**

**Alternatives Discussion:**

**Additional Context:**

**Comment by risavkarna** [comment]
@Cryptokripa , please fill up the placeholder texts for each sentence above. 

- [x] use task lists like these to break down your individual task items within a broad issue like this one
- [ ] keep track your UI improvements for each form A, B1, B2 etc.
- [ ] make the form style consistent with our material form redesign even for older forms like Point of Entry (and everything below it)

**Comment by risavkarna** [comment]
What is the latest status this issue?
